name: Generate Data

on:
  schedule:
    - cron: '0 9 * * *'  # 4 AM Eastern (9 UTC)
  workflow_dispatch:  # For manual runs

# Give the workflow permission to push to the repository
permissions:
  contents: write

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0  # Get full history
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install Cython
          pip install datamule --no-build-isolation
      
      - name: Run generate-data script
        run: python code/generate-data.py
      
      - name: Commit changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add -f data/phrases/10kq/*.csv.gz
          git commit -m "Generate data update" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF} || echo "No changes to push"